# This is a basic workflow to help you get started with Actions

name: Updates

on:
  push:
    paths:
      - 'markdown_generator/publications.tsv'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install pandas
      - name: execute py script
        run: |
          python ./markdown_generator/publications.py
